import { useSpring, animated } from 'react-spring';
import Head from 'next/head';
import { getSession, signOut } from 'next-auth/react';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';


export default function Home({ session, userDetails }) {
  const containerSpring = useSpring({
    from: { opacity: 0, transform: 'translate3d(0, -50px, 0)' },
    to: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
  });

  return (
    <>
      <Head>
        <title>MYM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <animated.div style={containerSpring} className={styles.mainContainer}>
        {session ? (
          <>
            {/* Content to be shown only for session users */}
            <button onClick={signOut}>log out</button>
          </>
        ) : (
          <>
            {/* Content to be shown only for non-session users */}
          </>
        )}
        {/* Content to show to both */}
        <div className={styles.hiuser}>
          <Image src={'/images/large_pngs/hiuser.png'} width={1080 / 3} height={720 / 3} alt='hi user' />
        </div>
        <h2 className={styles.fullform}>Meet.Your.Mate</h2>
        <p className={styles.desc}>Sign up now and start connecting with students from your college and beyond.</p>
        <p className={styles.desc}>
          "Ready to join the conversation? Take your student experience to the next level!”
        </p>
        <div className={styles.showcase}>
          <Image src={'/images/showcase/mymLaptop.png'} width={1280} height={787} alt='showcase' className={styles.showcaseImg}/>
          <div className={styles.showcaseCont}>
            <div className={styles.tagline}>
              Connect -&gt; Confess -&gt; Trend
            </div>
            <div className={styles.taglineP}>
              "Your college experience, redefined."
            </div>
          </div>
        </div>
        <div className={styles.showcase}>
          <div className={styles.showcaseCont}  id={styles.taglinePid}>
            <img src="/images/showcase/svgs/arrow.svg" alt="" className={styles.arrowSvg} />
            <div className={styles.taglineP} id={styles.taglineP2}>
              The exclusive social platform designed for college students to connect, share, and confess anonymously.
            </div>
          </div>
          <Image src={'/images/showcase/mymFriends.png'} width={1280} height={787} alt='showcase' className={styles.showcaseImg} />
        </div>
        <h3 className={styles.unlock}>Unlock the doors of possibility and embrace <br /> the friendships that await</h3>
        <div style={{padding:"2rem", width:"100%", height:"auto"}}>
          <div style={{aspectRatio:'1280/720', width:'100%', backgroundColor:"gray"}}></div>
        </div>
        <div className={styles.comingsoonCards}>
        <Image src={'/images/showcase/cards.png'} width={1348} height={688} alt='cards'  ></Image>
        </div>
        <div style={{ width: '100%', height: '10em' }}></div>
      </animated.div>
    </>
  );
}

export async function getServerSideProps(context) {
  // Fetch session and user details
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/auth/signup',
        permanent: false,
      },
    };
  }

  const pageurl = 'https://www.meetyourmate.in'

  let userDetails = null;
  if (session?.user?.email) {
    try {
      const response = await fetch(`${pageurl}/api/getdetails/getuserdetails?userEmail=${session.user.email}`);
      if (response.ok) {
        userDetails = await response.json();
      } else {
        console.error('Error fetching user details');
      }
    } catch (error) {
      console.error('Error fetching user details:', error);
    }
  }

  return {
    props: {
      session,
      userDetails,
    },
  };
}
