import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MYM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>  <a href="/auth/signin">Login</a></div>
        <div>  <a href="/auth/signup">Create Account</a></div>
        <div style={{ margin: '3rem' }}>  <a href="/textchat">Chat</a></div>
        <div style={{ margin: '3rem' }}>  <a href="/confessions">Confessions</a></div>
      </main>
    </>
  )
}
